= iUI README

iUI is a JavaScript and CSS User-Interface framework for smartphones and other mobile devices.
   
To learn more about iUI, visit the http://www.iui-js.org[iUI website].

To install and use iUI, see http://www.iui-js.org/documentation/latest/getting-started.html[Getting Started].

== Mailing Lists (Google Groups)

See our http://www.iui-js.org/get-involved[Get Involved] page for information on our two Google Groups.

          
== Source Code

https://github.com/iui/iUI[iUI Source] is hosted on GitHub, but also https://code.google.com/p/iui/source/browse/[mirrored] on Google Code.

== Issues Database

The https://code.google.com/p/iui/issues/list[iUI Issues Database] is hosted on Google Code.

== iUI WIki

The https://code.google.com/p/iui/w/list[iUI Wiki] is also hosted on Google Code.

== Downloads

You'll find the latest stable release on our http://www.iui-js.org/download[Download] page.

* Recent downloads are powered by https://bintray.com/iui/releases/iUI/[Bintray].
* https://iui.ci.cloudbees.com/job/iUI/[Development builds] are produced automatically by our https://iui.ci.cloudbees.com[Continuous Integration server] -- powered by http://www.cloudbees.com/[CloudBees].
* Older, historical downloads are on https://code.google.com/p/iui/downloads/list?can=4[Google Code].

== See also

* https://github.com/iui/iUI/blob/master/NOTICE.txt[NOTICE.txt]  - iUI credits and copyright notices
* https://github.com/iui/iUI/blob/master/LICENSE.txt[LICENSE.txt] - iUI licensing terms (MIT License)

== About this README

This +README.adoc+ file is in http://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] format.  GitHub provides https://github.com/github/markup[built in support] for AsciiDoc.  Future iUI documentation will likely be in AsciiDoc.  See the http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference] to learn how to format AsciiDoc.

